package Primer_Final;

import javax.swing.JOptionPane;

/**
 * Grupo 4
 * @author Leyda Aylen Fleitas Cabrera
 * @author Andrea Lujan Nunez Rodriguez
 * @version 30/11/2024
 */
public class VentanaPagoTarjetaNuevo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPagoTarjetaNuevo
     */
    public VentanaPagoTarjetaNuevo() {
        initComponents();
        ClaseArchivos.cargarClientesDesdeArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 201, 230));

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton2.setText("Actualizar Pago");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel4.setText("Cuenta de Tarjeta de Credito");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel6.setText("Monto a Pagar");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(141, 141, 196));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAGO DE TARJETA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(116, 116, 116))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // Obtener el monto ingresado
        String montoIngresadoTexto = jTextField4.getText();
        double montoIngresado;

        try {
            montoIngresado = Double.parseDouble(montoIngresadoTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.");
            return; // Detenemos la ejecución si el monto no es un número válido
        }

        JOptionPane.showMessageDialog(this, "Monto ingresado: " + montoIngresado);
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Obtener el ID de cuenta ingresado
        String cuentaID = jTextField1.getText();
        ClaseCuenta cuenta = ClaseArchivos.buscarCuenta(cuentaID);
        if (cuenta == null) {
            JOptionPane.showMessageDialog(this, "No se encontró una cuenta con el ID ingresado.");
            return;
        }

        // Verificar si la cuenta tiene al menos una tarjeta de crédito
        if (cuenta.getTarjetasDeCredito().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cuenta ingresada no tiene una tarjeta de crédito asociada.");
            return;
        }

        // Mostrar la tarjeta de crédito asociada
        ClaseTarjetaDeCredito tarjetaCredito = cuenta.getTarjetasDeCredito().get(0);
        JOptionPane.showMessageDialog(this, "Tarjeta de Crédito asociada: " + tarjetaCredito.getNumeroDeTarjeta());
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 1. Obtener la cuenta de la tarjeta de crédito a pagar
        String cuentaCreditoID = jTextField1.getText();
        ClaseCuenta cuentaCredito = ClaseArchivos.buscarCuenta(cuentaCreditoID);
        if (cuentaCredito == null || cuentaCredito.getTarjetasDeCredito().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontró una cuenta con tarjeta de crédito asociada.");
            return;
        }
        ClaseTarjetaDeCredito tarjetaCreditoAPagar = cuentaCredito.getTarjetasDeCredito().get(0);

        // 2. Obtener la cuenta de la tarjeta con la que se va a pagar
        String cuentaPagoID = jTextField1.getText();
        ClaseCuenta cuentaPago = ClaseArchivos.buscarCuenta(cuentaPagoID);
        if (cuentaPago == null) {
            JOptionPane.showMessageDialog(this, "No se encontró una cuenta con el ID ingresado para pagar.");
            return;
        }

        // 3. Obtener la tarjeta con la que se va a pagar
        ClaseTarjeta tarjetaConLaQuePagar = null;
        if (!cuentaPago.getTarjetasDeCredito().isEmpty()) {
            tarjetaConLaQuePagar = cuentaPago.getTarjetasDeCredito().get(0);
        } else if (!cuentaPago.getTarjetasDeDebito().isEmpty()) {
            tarjetaConLaQuePagar = cuentaPago.getTarjetasDeDebito().get(0);
        }

        if (tarjetaConLaQuePagar == null) {
            JOptionPane.showMessageDialog(this, "No se encontró una tarjeta en la cuenta para realizar el pago.");
            return;
        }

        // 4. Obtener el monto ingresado para el pago
        String montoIngresadoTexto = jTextField4.getText();
        double montoIngresado;
        try {
            montoIngresado = Double.parseDouble(montoIngresadoTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.");
            return;
        }

        // 5. Verificar si la tarjeta con la que se va a pagar tiene suficiente saldo
        double saldoDisponible;
        if (tarjetaConLaQuePagar instanceof ClaseTarjetaDeCredito) {
            ClaseTarjetaDeCredito tarjetaCredito = (ClaseTarjetaDeCredito) tarjetaConLaQuePagar;
            saldoDisponible = tarjetaCredito.getSaldoDisponible();
            if (saldoDisponible < montoIngresado) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente en la tarjeta de crédito seleccionada para realizar el pago.");
                return;
            }
            tarjetaCredito.setSaldoDisponible(saldoDisponible - montoIngresado);
        } else if (tarjetaConLaQuePagar instanceof ClaseTarjetaDeDebito) {
            ClaseTarjetaDeDebito tarjetaDebito = (ClaseTarjetaDeDebito) tarjetaConLaQuePagar;
            saldoDisponible = tarjetaDebito.getSaldoCuenta();
            if (saldoDisponible < montoIngresado) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente en la tarjeta de débito seleccionada para realizar el pago.");
                return;
            }
            tarjetaDebito.setSaldoCuenta(saldoDisponible - montoIngresado);
        } else {
            JOptionPane.showMessageDialog(this, "Tipo de tarjeta desconocido.");
            return;
        }

        // 6. Actualizar la deuda de la tarjeta de crédito a pagar
        tarjetaCreditoAPagar.setDeudaActual(tarjetaCreditoAPagar.getDeudaActual() - montoIngresado);
        ClaseArchivos.actualizarArchivo(); // Actualizar el archivo después de hacer el pago

        // 7. Mostrar el resultado del pago
        JOptionPane.showMessageDialog(this, "Pago de " + montoIngresado + " realizado exitosamente para la tarjeta de crédito: " + tarjetaCreditoAPagar.getNumeroDeTarjeta());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Cerrar la ventana actual
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPagoTarjetaNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPagoTarjetaNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPagoTarjetaNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPagoTarjetaNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPagoTarjetaNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
